# This Gemfile comes from hydra-head/test_support/etc/Gemfile
# It's copied into the atrium test app by the rake atrium:setup_test_app task

source 'http://rubygems.org'

gem 'rails', '~>3.0.10'

gem 'atrium', :path => '../../'
gem 'blacklight', '3.0.0'
gem 'cancan'
gem 'devise'
gem 'liquid'
gem 'sqlite3-ruby', :require => 'sqlite3'

# For testing
group :development, :test do
  gem 'solrizer-fedora', '>=1.1.0'
  gem 'ruby-debug'
  gem 'rspec'
  gem 'rspec-rails', '>=2.5.0'
  gem 'mocha'
  gem 'cucumber-rails'
  gem 'database_cleaner'
  gem 'capybara'
  gem 'factory_girl'
  gem 'bcrypt-ruby'
end
